# Generated by Django 3.2.5 on 2021-07-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0028_auto_20210727_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='plural_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='public',
        ),
    ]
